#include "EditorGui.h"

#include "RenderDistanceSettings.h"

#include <imgui.h>
#include <imgui_impl_opengl3.h>

namespace ve::editor
{
	/**
	* @brief Constructs and submits the engine developer-settings window.
	*
	* @note This function operates entirely in Immediate Mode, mutating the provided
	* `state` struct in real-time via pointer mapping in ImGui's widget calls. Notice
	* @param state Mutable reference to the engine's configuration payload.
	*/

	void EditorGui::DrawSettingsPanel(EditorSettings& state)
	{
		if (!is_initialized_) return;
		ImGui::Begin("Engine Settings");
		ImGui::SliderInt("Render distance", &state.render_distance_chunks,
			ve::gameplay::MinimumRenderDistanceChunks,
			ve::gameplay::MaximumRenderDistanceChunks);
		ImGui::Checkbox("VSync", &state.is_vsync_enabled);
		ImGui::End();
	}

	/**
	 * @brief Flushes ImGui's internal command buffers to the graphics hardware.
	 *
	 * @note `ImGui::Render()` finalizes the geometry (draw lists) generated by the UI
	 * calls during the current frame. `ImGui_ImplOpenGL3_RenderDrawData` then translates
	 * these lists into actual OpenGL vertex buffers and draw calls. This must be invoked
	 * at the very end of the rendering pipeline, immediately before swapping the backbuffer.
	 */

	void EditorGui::Render()
	{
		if (!is_initialized_) return;
		ImGui::Render();
		ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
	}
}
