		VkExtent2D render_extent_{};
		std::vector<std::uint32_t> pixels_;
		std::vector<std::uint32_t> render_pixels_;
		std::vector<std::uint32_t> outline_pixels_;
		std::vector<UpscaleRange> upscale_x_ranges_;
		std::vector<UpscaleRange> upscale_y_ranges_;
		std::vector<CachedSampleRay> ray_cache_;
		FrameWorldSnapshot world_snapshot_;
		glm::vec3 cached_forward_{ 0.0f, 0.0f, -1.0f };
		glm::vec3 cached_right_{ 1.0f, 0.0f, 0.0f };
		glm::vec3 cached_up_{ 0.0f, 1.0f, 0.0f };
		std::uint32_t cached_sample_step_ = 0;
		bool ray_cache_valid_ = false;
		VulkanFrameTiming last_timing_{};
		TextureLibrary texture_library_;
		std::vector<std::jthread> workers_;
		std::mutex work_mutex_;
		std::condition_variable work_available_;
		std::condition_variable work_complete_;
		RasterWork current_work_{};
		std::atomic_size_t next_sample_index_{ 0 };
		std::uint64_t work_generation_ = 0;
		std::size_t active_workers_ = 0;
		bool stop_workers_ = false;
	};
}
