if (VE_ENABLE_ASAN)
    target_compile_definitions(ve_project_options INTERFACE VE_ADDRESS_SANITIZER=1)
    if (MSVC)
        target_compile_options(ve_project_options INTERFACE /fsanitize=address /Zi /Oy-)
        target_link_options(ve_project_options INTERFACE /INCREMENTAL:NO)
    else()
        target_compile_options(ve_project_options INTERFACE -fsanitize=address -fno-omit-frame-pointer)
        target_link_options(ve_project_options INTERFACE -fsanitize=address)
    endif()
endif()

if (VE_ENABLE_UBSAN)
    if (MSVC)
        message(WARNING "VE_ENABLE_UBSAN is not supported by MSVC and will be ignored.")
    else()
        target_compile_definitions(ve_project_options INTERFACE VE_UNDEFINED_BEHAVIOR_SANITIZER=1)
        target_compile_options(ve_project_options INTERFACE -fsanitize=undefined -fno-omit-frame-pointer)
        target_link_options(ve_project_options INTERFACE -fsanitize=undefined)
    endif()
endif()
